### ISSUE TITLE
Caching integration

### ISSUE THREAD

**Issue by Billypl** [Billypl/NazwaZespolu#50]
Enabled caching in shop.

**Comment by Billypl** [comment]
Main changes:
- docker-compose:
```yaml
  memcached:
    container_name: BE_188898_memcached
    image: memcached:latest
    networks:
      - prestashop_network
```
- dockerfile:
```bash
RUN apt-get update && apt-get install -y \
    libmemcached-dev \
    zlib1g-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached
```
- admin panel (above command in dockerfile must be executed for this to work):
admin panel -> zaawansowane -> wydajność -> caching
![Image](https://github.com/user-attachments/assets/8d964a8a-dde2-463b-99df-47b2fce14330)
